# Generated by Django 6.0.5 on 2026-06-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('pais_origem', models.CharField(max_length=100)),
                ('ano_fundacao', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=200)),
                ('Telefone', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='telefone')),
                ('Endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Codigo', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='codigo')),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='peso')),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco')),
                ('Descricao', models.CharField(max_length=300)),
                ('Capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja_Automotiva.categoria', verbose_name='Categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja_Automotiva.fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razao_Social', models.CharField(max_length=200)),
                ('Inscricao_Estadual', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='inscricao estadual')),
                ('Cnpj', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='cnpj')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PJ', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpf', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='cpf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PF', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Pedido', models.CharField(max_length=11, unique=True, verbose_name='id_pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor_total')),
                ('forma_pagamento', models.CharField(max_length=150)),
                ('produto', models.ManyToManyField(related_name='pedidos', to='loja_Automotiva.produto', verbose_name='Componente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['Id_Pedido'],
            },
        ),
    ]
