# Generated by Django 6.0.5 on 2026-06-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ano_fundacao', models.IntegerField()),
                ('nome_fabricante', models.CharField(max_length=150, null=True, unique=True, verbose_name='nome')),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('endereco_fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_fabricante', models.CharField(max_length=11, null=True, verbose_name='telefone')),
                ('email_fabricante', models.EmailField(max_length=200, null=True, unique=True, verbose_name='email')),
                ('website', models.URLField(blank=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome_fabricante'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(default='Anonimo', max_length=150, unique=True, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, null=True, unique=True, verbose_name='cpf')),
                ('email_usuario', models.EmailField(max_length=200, null=True, unique=True, verbose_name='email')),
                ('telefone_usuario', models.CharField(max_length=11, null=True, verbose_name='telefone')),
                ('endereco_usuario', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nome_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_produto', models.CharField(default='0', max_length=11, primary_key=True, serialize=False, verbose_name='Código do Produto')),
                ('nome_produto', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('descricao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Foto da Capa')),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja_Automotiva.categoria', verbose_name='Categoria')),
                ('fabricante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja_Automotiva.fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razao_Social', models.CharField(max_length=200)),
                ('Inscricao_Estadual', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='inscricao estadual')),
                ('Cnpj', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='cnpj')),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_pj', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpf', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='cpf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PF', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Pedido', models.CharField(max_length=11, unique=True, verbose_name='id_pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor_total')),
                ('forma_pagamento', models.CharField(max_length=150)),
                ('produto', models.ManyToManyField(related_name='pedidos', to='loja_Automotiva.produto', verbose_name='Componente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='loja_Automotiva.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['Id_Pedido'],
            },
        ),
    ]
