# Generated by Django 6.0.4 on 2026-05-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('pais_origem', models.CharField(max_length=100)),
                ('ano_fundacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personalização',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodas', models.CharField(max_length=150)),
                ('escapamento', models.TextField(max_length=150)),
                ('espelho', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='loja_Automotiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Loja')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loja_Automotiva', to='loja_Automotiva.categoria', verbose_name='Categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loja_Automotiva', to='loja_Automotiva.fabricante', verbose_name='Fabricante')),
                ('personalização', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loja_Automotiva', to='loja_Automotiva.personalização', verbose_name='Personalização')),
            ],
        ),
    ]
