# Generated by Django 6.0.4 on 2026-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_Automotiva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalização',
            old_name='espelho',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='personalização',
            old_name='rodas',
            new_name='Tamanho',
        ),
        migrations.RemoveField(
            model_name='personalização',
            name='escapamento',
        ),
        migrations.AddField(
            model_name='personalização',
            name='Tipo',
            field=models.CharField(default='Padrão', max_length=150),
            preserve_default=False,
        ),
    ]
