# Generated by Django 6.0.4 on 2026-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_Automotiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_categoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='categoria'),
        ),
    ]
