# Generated by Django 6.0.4 on 2026-05-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja_Automotiva", "0002_rename_espelho_personalização_marca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=150)),
                ("tamanho", models.CharField(max_length=150)),
                ("marca", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="loja_automotiva",
            name="personalização",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loja_Automotiva",
                to="loja_Automotiva.personalizacao",
                verbose_name="Personalizacao",
            ),
        ),
        migrations.DeleteModel(
            name="Personalização",
        ),
    ]
