# Generated by Django 6.0.4 on 2026-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_Automotiva', '0002_alter_categoria_codigo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_pedido'),
        ),
    ]
