# Generated by Django 6.0.4 on 2026-05-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loja_Automotiva",
            "0003_personalizacao_alter_loja_automotiva_personalização_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loja_automotiva",
            name="personalização",
        ),
        migrations.AddField(
            model_name="loja_automotiva",
            name="personalizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Loja_Automotiva",
                to="loja_Automotiva.personalizacao",
                verbose_name="Personalizacao",
            ),
        ),
        migrations.AlterField(
            model_name="loja_automotiva",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Loja_Automotiva",
                to="loja_Automotiva.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="loja_automotiva",
            name="fabricante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Loja_Automotiva",
                to="loja_Automotiva.fabricante",
                verbose_name="Fabricante",
            ),
        ),
    ]
