# Generated by Django 6.0.4 on 2026-06-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_Automotiva', '0003_pedido_produto_usuario_pj_pf_delete_loja_automotiva_and_more'),
        ('loja_Automotiva', '0004_remove_loja_automotiva_personalização_and_more'),
    ]

    operations = [
    ]
